module.exports = function(props) {return [{value:'华康POP2体繁W9', label:'华康POP2体繁W9'},
{value:'华康POP3体繁W12', label:'华康POP3体繁W12'},
{value:'华康仿宋体简W3-A', label:'华康仿宋体简W3-A'},
{value:'华康仿宋体繁W4', label:'华康仿宋体繁W4'},
{value:'华康勘亭流简W9', label:'华康勘亭流简W9'},
{value:'华康流风体繁', label:'华康流风体繁'},
{value:'华康竹风体繁', label:'华康竹风体繁'},
{value:'华康简仿宋', label:'华康简仿宋'},
{value:'华康芸风体', label:'华康芸风体'},
{value:'華康POP1體W9', label:'華康POP1體W9'},
{value:'華康中圓體', label:'華康中圓體'},
{value:'華康中黑體', label:'華康中黑體'},
{value:'華康儷中宋', label:'華康儷中宋'},
{value:'華康儷中黑', label:'華康儷中黑'},
{value:'華康儷特圓', label:'華康儷特圓'},
{value:'華康儷粗圓', label:'華康儷粗圓'},
{value:'華康儷粗宋', label:'華康儷粗宋'},
{value:'華康儷粗黑', label:'華康儷粗黑'},
{value:'華康儷細黑', label:'華康儷細黑'},
{value:'華康儷金黑', label:'華康儷金黑'},
{value:'華康儷雅宋', label:'華康儷雅宋'},
{value:'華康儷黑', label:'華康儷黑'},
{value:'華康少女字W6', label:'華康少女字W6'},
{value:'華康流隸t', label:'華康流隸t'},
{value:'華康流隸體', label:'華康流隸體'},
{value:'華康特粗圓體', label:'華康特粗圓體'},
{value:'華康粗圓體', label:'華康粗圓體'}
];};